POST  http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Another Day Another Blog",
  "author": "nicz",
  "url": "test",
  "likes": 101,
  "user": "6582e61ed677aa7249f0d320"
}